import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ErrorBoundary from "@/components/Utility/ErrorBoundry";
import { TransactionProvider } from "context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admit Spot Assigment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorBoundary>
          <TransactionProvider>{children}</TransactionProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
